<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <DebugType>portable</DebugType>
    <AssemblyName>KeireDistributionService</AssemblyName>
    <RootNamespace>Keire.Distribution.Service</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../KeireDistribution.Contracts/KeireDistribution.Contracts.csproj" />
  </ItemGroup>
</Project>
