[functions.website-contact]
verify_jwt = false

[functions.marketplace-validator-queue]
verify_jwt = false

[functions.marketplace-publication]
verify_jwt = true

[functions.marketplace-publication-queue]
verify_jwt = false
