<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../KeireEditorManaged/Keire.Editor.Managed.csproj" />
    <ProjectReference Include="../Examples/Keire.ScriptingExamples.csproj" />
  </ItemGroup>
</Project>
