using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Keire.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class NativeServiceGenerator : IIncrementalGenerator
{
    private const string ContractAttribute = "Keire.NativeServiceContractAttribute";
    private const string MethodAttribute = "Keire.NativeMethodAttribute";
    private const string BufferAttribute = "Keire.NativeBufferAttribute";

    private static readonly DiagnosticDescriptor InvalidContract = new(
        "KEIREGEN001", "Invalid native service contract", "{0}", "Keire.Managed",
        DiagnosticSeverity.Error, isEnabledByDefault: true);
    private static readonly DiagnosticDescriptor InvalidMethod = new(
        "KEIREGEN002", "Unsupported native service signature", "{0}", "Keire.Managed",
        DiagnosticSeverity.Error, isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> contracts = context.SyntaxProvider.ForAttributeWithMetadataName(
            ContractAttribute,
            static (node, _) => node is InterfaceDeclarationSyntax,
            static (syntaxContext, _) => (INamedTypeSymbol)syntaxContext.TargetSymbol);
        context.RegisterSourceOutput(contracts, static (productionContext, contract) =>
            Emit(productionContext, contract));
    }

    private static void Emit(SourceProductionContext context, INamedTypeSymbol contract)
    {
        AttributeData? contractAttribute = Attribute(contract, ContractAttribute);
        if (contractAttribute is null || contract.ContainingType is not null || contract.TypeParameters.Length != 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidContract, contract.Locations.FirstOrDefault(),
                $"Native service contract '{contract.ToDisplayString()}' must be a top-level, non-generic interface."));
            return;
        }
        if (!TryStableId(contractAttribute, out string serviceId))
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidContract, contract.Locations.FirstOrDefault(),
                $"Native service contract '{contract.ToDisplayString()}' has an invalid stable ID."));
            return;
        }

        var generatedMethods = new List<string>();
        foreach (IMethodSymbol method in contract.GetMembers().OfType<IMethodSymbol>())
        {
            if (method.MethodKind != MethodKind.Ordinary || method.IsGenericMethod)
            {
                ReportMethod(context, method, "must be an ordinary non-generic method");
                continue;
            }
            AttributeData? methodAttribute = Attribute(method, MethodAttribute);
            if (methodAttribute is null || !TryStableId(methodAttribute, out string methodId))
            {
                ReportMethod(context, method, "requires NativeMethod with a valid stable ID");
                continue;
            }
            if (!TryGenerateMethod(context, method, serviceId, methodId, out string? generated))
                continue;
            generatedMethods.Add(generated!);
        }
        if (generatedMethods.Count != contract.GetMembers().OfType<IMethodSymbol>()
                .Count(method => method.MethodKind == MethodKind.Ordinary))
        {
            return;
        }

        string namespaceName = contract.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : contract.ContainingNamespace.ToDisplayString();
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        if (namespaceName.Length != 0)
        {
            source.Append("namespace ").Append(namespaceName).AppendLine(";");
            source.AppendLine();
        }
        source.Append("public static class ").Append(contract.Name).AppendLine("Native");
        source.AppendLine("{");
        source.Append("    public static global::System.Guid ServiceId { get; } = new global::System.Guid(\"")
            .Append(serviceId).AppendLine("\");");
        foreach (string method in generatedMethods)
            source.Append(method);
        source.AppendLine("}");
        context.AddSource($"{contract.Name}.Native.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static bool TryGenerateMethod(SourceProductionContext context, IMethodSymbol method, string serviceId,
                                          string methodId, out string? generated)
    {
        generated = null;
        foreach (IParameterSymbol parameter in method.Parameters)
        {
            if (parameter.RefKind != RefKind.None || parameter.IsParams || parameter.HasExplicitDefaultValue)
            {
                ReportMethod(context, method, $"parameter '{parameter.Name}' cannot be ref, out, params, or optional");
                return false;
            }
            if (!TryArgumentExpression(parameter, out _))
            {
                ReportMethod(context, method,
                    $"parameter '{parameter.Name}' uses unsupported type '{parameter.Type.ToDisplayString()}'");
                return false;
            }
        }
        if (!TryReturn(method.ReturnType, out string invocation, out string returnType))
        {
            ReportMethod(context, method,
                $"return type '{method.ReturnType.ToDisplayString()}' is unsupported by the bounded ABI");
            return false;
        }

        string parameters = string.Join(", ", method.Parameters.Select(parameter =>
            $"{TypeName(parameter.Type)} {Escape(parameter.Name)}"));
        string arguments = string.Join(", ", method.Parameters.Select(parameter =>
        {
            _ = TryArgumentExpression(parameter, out string? expression);
            return expression;
        }));
        var source = new StringBuilder();
        source.AppendLine();
        source.Append("    public static ").Append(returnType).Append(' ').Append(Escape(method.Name))
            .Append('(').Append(parameters).AppendLine(")");
        source.AppendLine("    {");
        source.Append("        global::Keire.NativeAbiValue[] arguments = [").Append(arguments).AppendLine("];");
        source.Append("        ");
        if (method.ReturnsVoid)
            source.Append("global::Keire.NativeServiceRuntime.Invoke");
        else
            source.Append("return global::Keire.NativeServiceRuntime.").Append(invocation);
        source.Append("(new global::System.Guid(\"").Append(serviceId)
            .Append("\"), new global::System.Guid(\"").Append(methodId).AppendLine("\"), arguments);");
        source.AppendLine("    }");
        generated = source.ToString();
        return true;
    }

    private static bool TryArgumentExpression(IParameterSymbol parameter, out string? expression)
    {
        expression = null;
        string name = Escape(parameter.Name);
        if (IsScalar(parameter.Type))
        {
            expression = $"global::Keire.NativeAbiValue.From({name})";
            return true;
        }
        if (!TryBufferElement(parameter.Type, out _) ||
            Attribute(parameter, BufferAttribute) is not AttributeData buffer ||
            buffer.ConstructorArguments.Length == 0 || buffer.ConstructorArguments[0].Value is not int maximum)
        {
            return false;
        }
        string span = parameter.Type is INamedTypeSymbol named && named.IsGenericType &&
                      (named.ConstructedFrom.ToDisplayString() == "System.Memory<T>" ||
                       named.ConstructedFrom.ToDisplayString() == "System.ReadOnlyMemory<T>")
            ? $"{name}.Span"
            : name;
        expression = $"global::Keire.NativeAbiValue.FromBuffer({span}, {maximum})";
        return true;
    }

    private static bool TryReturn(ITypeSymbol type, out string invocation, out string returnType)
    {
        returnType = TypeName(type);
        if (type.SpecialType == SpecialType.System_Void)
        {
            invocation = string.Empty;
            return true;
        }
        if (IsScalar(type))
        {
            invocation = $"Invoke<{returnType}>";
            return true;
        }
        if (type is INamedTypeSymbol named && named.IsGenericType &&
            named.ConstructedFrom.ToDisplayString() == "Keire.NativeCallResult<T>" && IsScalar(named.TypeArguments[0]))
        {
            invocation = $"InvokeResult<{TypeName(named.TypeArguments[0])}>";
            return true;
        }
        invocation = string.Empty;
        return false;
    }

    private static bool IsScalar(ITypeSymbol type)
    {
        if (type.SpecialType is SpecialType.System_Boolean or SpecialType.System_SByte or SpecialType.System_Byte or
            SpecialType.System_Int16 or SpecialType.System_UInt16 or SpecialType.System_Int32 or
            SpecialType.System_UInt32 or SpecialType.System_Int64 or SpecialType.System_UInt64 or
            SpecialType.System_Single or SpecialType.System_Double or SpecialType.System_String)
        {
            return true;
        }
        string name = type.ToDisplayString();
        return name is "System.Guid" or "Keire.Vector2" or "Keire.Vector3" or "Keire.Vector4" or
            "Keire.Quaternion" or "Keire.Color" or "Keire.EntityId" or "Keire.AssetId" or
            "Keire.ComponentTypeId";
    }

    private static bool TryBufferElement(ITypeSymbol type, out ITypeSymbol? element)
    {
        if (type is IArrayTypeSymbol array && array.Rank == 1)
        {
            element = array.ElementType;
            return IsScalar(element) && element.SpecialType != SpecialType.System_String;
        }
        if (type is INamedTypeSymbol named && named.IsGenericType &&
            named.ConstructedFrom.ToDisplayString() is "System.Span<T>" or "System.ReadOnlySpan<T>" or
                "System.Memory<T>" or "System.ReadOnlyMemory<T>")
        {
            element = named.TypeArguments[0];
            return IsScalar(element) && element.SpecialType != SpecialType.System_String;
        }
        element = null;
        return false;
    }

    private static AttributeData? Attribute(ISymbol symbol, string metadataName) =>
        symbol.GetAttributes().FirstOrDefault(attribute =>
            attribute.AttributeClass?.ToDisplayString() == metadataName);

    private static bool TryStableId(AttributeData attribute, out string stableId)
    {
        stableId = attribute.ConstructorArguments.FirstOrDefault().Value as string ?? string.Empty;
        return Guid.TryParse(stableId, out Guid parsed) && parsed != Guid.Empty;
    }

    private static string TypeName(ITypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string Escape(string identifier) =>
        Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetKeywordKind(identifier) ==
        Microsoft.CodeAnalysis.CSharp.SyntaxKind.None ? identifier : "@" + identifier;

    private static void ReportMethod(SourceProductionContext context, IMethodSymbol method, string reason) =>
        context.ReportDiagnostic(Diagnostic.Create(InvalidMethod, method.Locations.FirstOrDefault(),
            $"Native method '{method.ContainingType.ToDisplayString()}.{method.Name}' {reason}."));
}
