#include "Keire/Rendering/MaterialGraph.h"

#include <algorithm>
#include <array>
#include <ranges>

namespace Keire
{
    namespace
    {
        using NodeDescriptor = MaterialGraphNodeDescriptor;
        constexpr auto VertexAndFragment =
            static_cast<MaterialGraphShaderStage>(static_cast<std::uint8_t>(MaterialGraphShaderStage::Vertex) |
                                                  static_cast<std::uint8_t>(MaterialGraphShaderStage::Fragment));
        constexpr std::array MaterialGraphNodeDescriptors{
            NodeDescriptor{MaterialGraphNodeKind::Master, "keire.output.material", "PBR Master", "Output",
                           MaterialGraphValueType::Color, MaterialGraphShaderStage::Fragment, 48, false},
            NodeDescriptor{MaterialGraphNodeKind::Parameter, "keire.input.parameter", "Parameter", "Parameters"},
            NodeDescriptor{MaterialGraphNodeKind::Constant, "keire.input.constant", "Constant", "Constants",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::All},
            NodeDescriptor{MaterialGraphNodeKind::TextureSample, "keire.texture.sample_2d", "Sample Texture 2D",
                           "Textures", MaterialGraphValueType::Color, MaterialGraphShaderStage::Fragment, 4},
            NodeDescriptor{MaterialGraphNodeKind::UV, "keire.input.uv0", "UV0", "Coordinates",
                           MaterialGraphValueType::Vector2, VertexAndFragment},
            NodeDescriptor{MaterialGraphNodeKind::UVTransform, "keire.coordinates.uv_transform", "UV Transform",
                           "Coordinates", MaterialGraphValueType::Vector2, VertexAndFragment, 3},
            NodeDescriptor{MaterialGraphNodeKind::NormalMap, "keire.surface.normal_map", "Normal Map", "Surface",
                           MaterialGraphValueType::Vector3, MaterialGraphShaderStage::Fragment, 14},
            NodeDescriptor{MaterialGraphNodeKind::DetailNormal, "keire.surface.detail_normal", "Detail Normal",
                           "Surface", MaterialGraphValueType::Vector3, MaterialGraphShaderStage::Fragment, 10},
            NodeDescriptor{MaterialGraphNodeKind::Parallax, "keire.coordinates.parallax", "Parallax Offset",
                           "Coordinates", MaterialGraphValueType::Vector2, MaterialGraphShaderStage::Fragment, 16},
            NodeDescriptor{MaterialGraphNodeKind::Add, "keire.math.add", "Add", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Multiply, "keire.math.multiply", "Multiply", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Lerp, "keire.math.lerp", "Lerp", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::OneMinus, "keire.math.one_minus", "One Minus", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Clamp, "keire.math.saturate", "Saturate", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Keyword, "keire.logic.keyword", "Keyword", "Logic & Variants"},
            NodeDescriptor{MaterialGraphNodeKind::StaticSwitch, "keire.logic.static_switch", "Static Switch",
                           "Logic & Variants"},
            NodeDescriptor{MaterialGraphNodeKind::Custom, "keire.advanced.custom_function", "Custom Function",
                           "Advanced"},
            NodeDescriptor{MaterialGraphNodeKind::Subtract, "keire.math.subtract", "Subtract", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Divide, "keire.math.divide", "Divide", "Math",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::All, 8},
            NodeDescriptor{MaterialGraphNodeKind::Power, "keire.math.power", "Power", "Math",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::All, 8},
            NodeDescriptor{MaterialGraphNodeKind::Minimum, "keire.math.minimum", "Minimum", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Maximum, "keire.math.maximum", "Maximum", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Absolute, "keire.math.absolute", "Absolute", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Floor, "keire.math.floor", "Floor", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Ceiling, "keire.math.ceiling", "Ceiling", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Fraction, "keire.math.fraction", "Fraction", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Sine, "keire.math.sine", "Sine", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Cosine, "keire.math.cosine", "Cosine", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Normalize, "keire.vector.normalize", "Normalize", "Vector",
                           MaterialGraphValueType::Vector3, MaterialGraphShaderStage::All, 8},
            NodeDescriptor{MaterialGraphNodeKind::Length, "keire.vector.length", "Length", "Vector",
                           MaterialGraphValueType::Vector3, MaterialGraphShaderStage::All, 8},
            NodeDescriptor{MaterialGraphNodeKind::Dot, "keire.vector.dot", "Dot Product", "Vector",
                           MaterialGraphValueType::Vector3},
            NodeDescriptor{MaterialGraphNodeKind::Remap, "keire.math.remap", "Remap", "Math",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::All, 6},
            NodeDescriptor{MaterialGraphNodeKind::SmoothStep, "keire.math.smooth_step", "Smooth Step", "Math",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::All, 6},
            NodeDescriptor{MaterialGraphNodeKind::Step, "keire.math.step", "Step", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Fresnel, "keire.surface.fresnel", "Fresnel", "Surface",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::Fragment, 8},
            NodeDescriptor{MaterialGraphNodeKind::VertexColor, "keire.input.vertex_color", "Vertex Color", "Inputs",
                           MaterialGraphValueType::Color, VertexAndFragment},
            NodeDescriptor{MaterialGraphNodeKind::WorldPosition, "keire.input.world_position", "World Position",
                           "Inputs", MaterialGraphValueType::Vector3, VertexAndFragment},
            NodeDescriptor{MaterialGraphNodeKind::WorldNormal, "keire.input.world_normal", "World Normal", "Inputs",
                           MaterialGraphValueType::Vector3, VertexAndFragment},
            NodeDescriptor{MaterialGraphNodeKind::ViewDirection, "keire.input.view_direction", "View Direction",
                           "Inputs", MaterialGraphValueType::Vector3, MaterialGraphShaderStage::Fragment},
            NodeDescriptor{MaterialGraphNodeKind::RotateUV, "keire.coordinates.rotate_uv", "Rotate UV", "Coordinates",
                           MaterialGraphValueType::Vector2, VertexAndFragment, 6},
            NodeDescriptor{MaterialGraphNodeKind::SimpleNoise, "keire.procedural.simple_noise", "Simple Noise",
                           "Procedural", MaterialGraphValueType::Scalar, MaterialGraphShaderStage::Fragment, 28},
            NodeDescriptor{MaterialGraphNodeKind::Desaturate, "keire.color.desaturate", "Desaturate", "Color",
                           MaterialGraphValueType::Color, MaterialGraphShaderStage::All, 6},
            NodeDescriptor{MaterialGraphNodeKind::Posterize, "keire.math.posterize", "Posterize", "Math",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::All, 4},
            NodeDescriptor{MaterialGraphNodeKind::Round, "keire.math.round", "Round", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Truncate, "keire.math.truncate", "Truncate", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Sign, "keire.math.sign", "Sign", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Modulo, "keire.math.modulo", "Modulo", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::SquareRoot, "keire.math.square_root", "Square Root", "Math",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::All, 4},
            NodeDescriptor{MaterialGraphNodeKind::ReciprocalSquareRoot, "keire.math.reciprocal_square_root",
                           "Reciprocal Square Root", "Math", MaterialGraphValueType::Scalar,
                           MaterialGraphShaderStage::All, 4},
            NodeDescriptor{MaterialGraphNodeKind::Exponential2, "keire.math.exponential_2", "Exponential 2", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Logarithm2, "keire.math.logarithm_2", "Logarithm 2", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Tangent, "keire.math.tangent", "Tangent", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::ArcSine, "keire.math.arc_sine", "Arc Sine", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::ArcCosine, "keire.math.arc_cosine", "Arc Cosine", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::ArcTangent2, "keire.math.arc_tangent_2", "Arc Tangent 2", "Math"},
            NodeDescriptor{MaterialGraphNodeKind::Cross, "keire.vector.cross", "Cross Product", "Vector",
                           MaterialGraphValueType::Vector3},
            NodeDescriptor{MaterialGraphNodeKind::Distance, "keire.vector.distance", "Distance", "Vector",
                           MaterialGraphValueType::Vector3},
            NodeDescriptor{MaterialGraphNodeKind::Reflect, "keire.vector.reflect", "Reflect", "Vector",
                           MaterialGraphValueType::Vector3},
            NodeDescriptor{MaterialGraphNodeKind::Refract, "keire.vector.refract", "Refract", "Vector",
                           MaterialGraphValueType::Vector3, MaterialGraphShaderStage::All, 8},
            NodeDescriptor{MaterialGraphNodeKind::AppendVector, "keire.vector.append", "Append Vector", "Vector",
                           MaterialGraphValueType::Vector4},
            NodeDescriptor{MaterialGraphNodeKind::ComponentMask, "keire.vector.component_mask", "Component Mask",
                           "Vector", MaterialGraphValueType::Vector4},
            NodeDescriptor{MaterialGraphNodeKind::UV1, "keire.input.uv1", "UV1", "Coordinates",
                           MaterialGraphValueType::Vector2, VertexAndFragment},
            NodeDescriptor{MaterialGraphNodeKind::WorldTangent, "keire.input.world_tangent", "World Tangent", "Inputs",
                           MaterialGraphValueType::Vector3, VertexAndFragment},
            NodeDescriptor{MaterialGraphNodeKind::CameraPosition, "keire.input.camera_position", "Camera Position",
                           "Inputs", MaterialGraphValueType::Vector3, MaterialGraphShaderStage::Fragment},
            NodeDescriptor{MaterialGraphNodeKind::ObjectPosition, "keire.input.object_position", "Object Position",
                           "Inputs", MaterialGraphValueType::Vector3, VertexAndFragment},
            NodeDescriptor{MaterialGraphNodeKind::Time, "keire.input.time", "Time", "Inputs",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::Fragment},
            NodeDescriptor{MaterialGraphNodeKind::DeltaTime, "keire.input.delta_time", "Delta Time", "Inputs",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::Fragment},
            NodeDescriptor{MaterialGraphNodeKind::ScreenPosition, "keire.input.screen_position", "Screen Position",
                           "Coordinates", MaterialGraphValueType::Vector2, MaterialGraphShaderStage::Fragment},
            NodeDescriptor{MaterialGraphNodeKind::DerivativeX, "keire.math.derivative_x", "Derivative X", "Math",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::Fragment},
            NodeDescriptor{MaterialGraphNodeKind::DerivativeY, "keire.math.derivative_y", "Derivative Y", "Math",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::Fragment},
            NodeDescriptor{MaterialGraphNodeKind::FilterWidth, "keire.math.filter_width", "Filter Width", "Math",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::Fragment, 2},
            NodeDescriptor{MaterialGraphNodeKind::DepthFade, "keire.scene.depth_fade", "Depth Fade", "Scene",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::Fragment, 6},
            NodeDescriptor{MaterialGraphNodeKind::Luminance, "keire.color.luminance", "Luminance", "Color",
                           MaterialGraphValueType::Color},
            NodeDescriptor{MaterialGraphNodeKind::HueShift, "keire.color.hue_shift", "Hue Shift", "Color",
                           MaterialGraphValueType::Color, MaterialGraphShaderStage::Fragment, 12},
            NodeDescriptor{MaterialGraphNodeKind::Checkerboard, "keire.procedural.checkerboard", "Checkerboard",
                           "Procedural", MaterialGraphValueType::Color, MaterialGraphShaderStage::Fragment, 8},
            NodeDescriptor{MaterialGraphNodeKind::VoronoiNoise, "keire.procedural.voronoi", "Voronoi Noise",
                           "Procedural", MaterialGraphValueType::Scalar, MaterialGraphShaderStage::Fragment, 36},
            NodeDescriptor{MaterialGraphNodeKind::Panner, "keire.coordinates.panner", "Panner", "Coordinates",
                           MaterialGraphValueType::Vector2, MaterialGraphShaderStage::Fragment, 4},
            NodeDescriptor{MaterialGraphNodeKind::PolarCoordinates, "keire.coordinates.polar", "Polar Coordinates",
                           "Coordinates", MaterialGraphValueType::Vector2, VertexAndFragment, 12},
            NodeDescriptor{MaterialGraphNodeKind::SphereMask, "keire.utility.sphere_mask", "Sphere Mask", "Utility",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::All, 8},
            NodeDescriptor{MaterialGraphNodeKind::RadialGradient, "keire.procedural.radial_gradient", "Radial Gradient",
                           "Procedural", MaterialGraphValueType::Scalar, MaterialGraphShaderStage::All, 8},
            NodeDescriptor{MaterialGraphNodeKind::LinearGradient, "keire.procedural.linear_gradient", "Linear Gradient",
                           "Procedural", MaterialGraphValueType::Scalar, MaterialGraphShaderStage::All, 4},
            NodeDescriptor{MaterialGraphNodeKind::Contrast, "keire.color.contrast", "Contrast", "Color",
                           MaterialGraphValueType::Color, MaterialGraphShaderStage::All, 4},
            NodeDescriptor{MaterialGraphNodeKind::Saturation, "keire.color.saturation", "Saturation", "Color",
                           MaterialGraphValueType::Color, MaterialGraphShaderStage::All, 6},
            NodeDescriptor{MaterialGraphNodeKind::BlendOverlay, "keire.color.blend_overlay", "Overlay Blend", "Color",
                           MaterialGraphValueType::Color, MaterialGraphShaderStage::All, 12},
            NodeDescriptor{MaterialGraphNodeKind::Blackbody, "keire.color.blackbody", "Blackbody", "Color",
                           MaterialGraphValueType::Color, MaterialGraphShaderStage::All, 24},
            NodeDescriptor{MaterialGraphNodeKind::ReflectionVector, "keire.input.reflection_vector",
                           "Reflection Vector", "Inputs", MaterialGraphValueType::Vector3,
                           MaterialGraphShaderStage::Fragment, 4},
            NodeDescriptor{MaterialGraphNodeKind::FacingRatio, "keire.surface.facing_ratio", "Facing Ratio", "Surface",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::Fragment, 8},
            NodeDescriptor{MaterialGraphNodeKind::Dither, "keire.utility.dither", "Dither", "Utility",
                           MaterialGraphValueType::Scalar, MaterialGraphShaderStage::Fragment, 6},
            NodeDescriptor{MaterialGraphNodeKind::GradientNoise, "keire.procedural.gradient_noise", "Gradient Noise",
                           "Procedural", MaterialGraphValueType::Scalar, MaterialGraphShaderStage::Fragment, 30},
            NodeDescriptor{MaterialGraphNodeKind::Wave, "keire.procedural.wave", "Wave", "Procedural",
                           MaterialGraphValueType::Scalar, VertexAndFragment, 6},
            NodeDescriptor{MaterialGraphNodeKind::TriplanarSample, "keire.texture.triplanar_sample", "Triplanar Sample",
                           "Textures", MaterialGraphValueType::Color, MaterialGraphShaderStage::Fragment, 18},
            NodeDescriptor{MaterialGraphNodeKind::TextureSampleLevel, "keire.texture.sample_level_2d",
                           "Sample Texture 2D Level", "Textures", MaterialGraphValueType::Color,
                           MaterialGraphShaderStage::Fragment, 4},
            NodeDescriptor{MaterialGraphNodeKind::HeightToNormal, "keire.surface.height_to_normal", "Height To Normal",
                           "Surface", MaterialGraphValueType::Vector3, MaterialGraphShaderStage::Fragment, 10},
            NodeDescriptor{MaterialGraphNodeKind::FlattenNormal, "keire.surface.flatten_normal", "Flatten Normal",
                           "Surface", MaterialGraphValueType::Vector3, MaterialGraphShaderStage::Fragment, 6},
            NodeDescriptor{MaterialGraphNodeKind::MakeMaterialAttributes, "keire.attributes.make",
                           "Make Material Attributes", "Material Attributes",
                           MaterialGraphValueType::MaterialAttributes, MaterialGraphShaderStage::Fragment, 4},
            NodeDescriptor{MaterialGraphNodeKind::BreakMaterialAttributes, "keire.attributes.break",
                           "Break Material Attributes", "Material Attributes",
                           MaterialGraphValueType::MaterialAttributes, MaterialGraphShaderStage::Fragment, 2},
            NodeDescriptor{MaterialGraphNodeKind::BlendMaterialAttributes, "keire.attributes.blend",
                           "Blend Material Attributes", "Material Layers", MaterialGraphValueType::MaterialAttributes,
                           MaterialGraphShaderStage::Fragment, 36},
            NodeDescriptor{MaterialGraphNodeKind::StandardSurfaceBsdf, "keire.bsdf.standard_surface",
                           "Standard Surface BSDF", "BSDF", MaterialGraphValueType::Bsdf,
                           MaterialGraphShaderStage::Fragment, 6},
            NodeDescriptor{MaterialGraphNodeKind::ClearCoatBsdf, "keire.bsdf.clear_coat", "Clear Coat BSDF", "BSDF",
                           MaterialGraphValueType::Bsdf, MaterialGraphShaderStage::Fragment, 4},
            NodeDescriptor{MaterialGraphNodeKind::SheenBsdf, "keire.bsdf.sheen", "Sheen BSDF", "BSDF",
                           MaterialGraphValueType::Bsdf, MaterialGraphShaderStage::Fragment, 6},
            NodeDescriptor{MaterialGraphNodeKind::SubsurfaceBsdf, "keire.bsdf.subsurface", "Subsurface BSDF", "BSDF",
                           MaterialGraphValueType::Bsdf, MaterialGraphShaderStage::Fragment, 6},
            NodeDescriptor{MaterialGraphNodeKind::TransmissionBsdf, "keire.bsdf.transmission", "Transmission BSDF",
                           "BSDF", MaterialGraphValueType::Bsdf, MaterialGraphShaderStage::Fragment, 8},
            NodeDescriptor{MaterialGraphNodeKind::BsdfToMaterialAttributes, "keire.bsdf.to_material_attributes",
                           "BSDF To Material Attributes", "Material Attributes", MaterialGraphValueType::Bsdf,
                           MaterialGraphShaderStage::Fragment, 2},
        };
    } // namespace

    std::span<const MaterialGraphNodeDescriptor> MaterialGraphNodeCatalog() noexcept
    {
        return MaterialGraphNodeDescriptors;
    }

    const MaterialGraphNodeDescriptor* FindMaterialGraphNodeDescriptor(const std::string_view typeId) noexcept
    {
        const auto found =
            std::ranges::find(MaterialGraphNodeDescriptors, typeId, &MaterialGraphNodeDescriptor::TypeId);
        return found == MaterialGraphNodeDescriptors.end() ? nullptr : &*found;
    }

    std::string_view MaterialGraphNodeTypeId(const MaterialGraphNodeKind kind) noexcept
    {
        const auto found = std::ranges::find(MaterialGraphNodeDescriptors, kind, &MaterialGraphNodeDescriptor::Kind);
        return found == MaterialGraphNodeDescriptors.end() ? std::string_view{} : found->TypeId;
    }
} // namespace Keire
