#include "Keire/Rendering/ShaderGraph.h"

#include <algorithm>
#include <array>
#include <ranges>

namespace Keire
{
    namespace
    {
        using NodeDescriptor = ShaderGraphNodeDescriptor;
        constexpr auto VertexAndFragment =
            static_cast<ShaderGraphShaderStage>(static_cast<std::uint8_t>(ShaderGraphShaderStage::Vertex) |
                                                static_cast<std::uint8_t>(ShaderGraphShaderStage::Fragment));
        constexpr std::array ShaderGraphNodeDescriptors{
            NodeDescriptor{ShaderGraphNodeKind::Master, "keire.output.material", "Lit Shader Output", "Output",
                           ShaderGraphValueType::Color, ShaderGraphShaderStage::Fragment, 48, false},
            NodeDescriptor{ShaderGraphNodeKind::Parameter, "keire.input.parameter", "Parameter", "Parameters"},
            NodeDescriptor{ShaderGraphNodeKind::Constant, "keire.input.constant", "Constant", "Constants",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::All},
            NodeDescriptor{ShaderGraphNodeKind::TextureSample, "keire.texture.sample_2d", "Sample Texture 2D",
                           "Textures", ShaderGraphValueType::Color, ShaderGraphShaderStage::Fragment, 4},
            NodeDescriptor{ShaderGraphNodeKind::UV, "keire.input.uv0", "UV0", "Coordinates",
                           ShaderGraphValueType::Vector2, VertexAndFragment},
            NodeDescriptor{ShaderGraphNodeKind::UVTransform, "keire.coordinates.uv_transform", "UV Transform",
                           "Coordinates", ShaderGraphValueType::Vector2, VertexAndFragment, 3},
            NodeDescriptor{ShaderGraphNodeKind::NormalMap, "keire.surface.normal_map", "Normal Map", "Surface",
                           ShaderGraphValueType::Vector3, ShaderGraphShaderStage::Fragment, 14},
            NodeDescriptor{ShaderGraphNodeKind::DetailNormal, "keire.surface.detail_normal", "Detail Normal", "Surface",
                           ShaderGraphValueType::Vector3, ShaderGraphShaderStage::Fragment, 10},
            NodeDescriptor{ShaderGraphNodeKind::Parallax, "keire.coordinates.parallax", "Parallax Offset",
                           "Coordinates", ShaderGraphValueType::Vector2, ShaderGraphShaderStage::Fragment, 16},
            NodeDescriptor{ShaderGraphNodeKind::Add, "keire.math.add", "Add", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Multiply, "keire.math.multiply", "Multiply", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Lerp, "keire.math.lerp", "Lerp", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::OneMinus, "keire.math.one_minus", "One Minus", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Clamp, "keire.math.saturate", "Saturate", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Keyword, "keire.logic.keyword", "Keyword", "Logic & Variants"},
            NodeDescriptor{ShaderGraphNodeKind::StaticSwitch, "keire.logic.static_switch", "Static Switch",
                           "Logic & Variants"},
            NodeDescriptor{ShaderGraphNodeKind::Custom, "keire.advanced.custom_function", "Custom Function",
                           "Advanced"},
            NodeDescriptor{ShaderGraphNodeKind::Subtract, "keire.math.subtract", "Subtract", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Divide, "keire.math.divide", "Divide", "Math",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::All, 8},
            NodeDescriptor{ShaderGraphNodeKind::Power, "keire.math.power", "Power", "Math",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::All, 8},
            NodeDescriptor{ShaderGraphNodeKind::Minimum, "keire.math.minimum", "Minimum", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Maximum, "keire.math.maximum", "Maximum", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Absolute, "keire.math.absolute", "Absolute", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Floor, "keire.math.floor", "Floor", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Ceiling, "keire.math.ceiling", "Ceiling", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Fraction, "keire.math.fraction", "Fraction", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Sine, "keire.math.sine", "Sine", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Cosine, "keire.math.cosine", "Cosine", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Normalize, "keire.vector.normalize", "Normalize", "Vector",
                           ShaderGraphValueType::Vector3, ShaderGraphShaderStage::All, 8},
            NodeDescriptor{ShaderGraphNodeKind::Length, "keire.vector.length", "Length", "Vector",
                           ShaderGraphValueType::Vector3, ShaderGraphShaderStage::All, 8},
            NodeDescriptor{ShaderGraphNodeKind::Dot, "keire.vector.dot", "Dot Product", "Vector",
                           ShaderGraphValueType::Vector3},
            NodeDescriptor{ShaderGraphNodeKind::Remap, "keire.math.remap", "Remap", "Math",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::All, 6},
            NodeDescriptor{ShaderGraphNodeKind::SmoothStep, "keire.math.smooth_step", "Smooth Step", "Math",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::All, 6},
            NodeDescriptor{ShaderGraphNodeKind::Step, "keire.math.step", "Step", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Fresnel, "keire.surface.fresnel", "Fresnel", "Surface",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::Fragment, 8},
            NodeDescriptor{ShaderGraphNodeKind::VertexColor, "keire.input.vertex_color", "Vertex Color", "Inputs",
                           ShaderGraphValueType::Color, VertexAndFragment},
            NodeDescriptor{ShaderGraphNodeKind::WorldPosition, "keire.input.world_position", "World Position", "Inputs",
                           ShaderGraphValueType::Vector3, VertexAndFragment},
            NodeDescriptor{ShaderGraphNodeKind::WorldNormal, "keire.input.world_normal", "World Normal", "Inputs",
                           ShaderGraphValueType::Vector3, VertexAndFragment},
            NodeDescriptor{ShaderGraphNodeKind::ViewDirection, "keire.input.view_direction", "View Direction", "Inputs",
                           ShaderGraphValueType::Vector3, ShaderGraphShaderStage::Fragment},
            NodeDescriptor{ShaderGraphNodeKind::RotateUV, "keire.coordinates.rotate_uv", "Rotate UV", "Coordinates",
                           ShaderGraphValueType::Vector2, VertexAndFragment, 6},
            NodeDescriptor{ShaderGraphNodeKind::SimpleNoise, "keire.procedural.simple_noise", "Simple Noise",
                           "Procedural", ShaderGraphValueType::Scalar, ShaderGraphShaderStage::Fragment, 28},
            NodeDescriptor{ShaderGraphNodeKind::Desaturate, "keire.color.desaturate", "Desaturate", "Color",
                           ShaderGraphValueType::Color, ShaderGraphShaderStage::All, 6},
            NodeDescriptor{ShaderGraphNodeKind::Posterize, "keire.math.posterize", "Posterize", "Math",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::All, 4},
            NodeDescriptor{ShaderGraphNodeKind::Round, "keire.math.round", "Round", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Truncate, "keire.math.truncate", "Truncate", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Sign, "keire.math.sign", "Sign", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Modulo, "keire.math.modulo", "Modulo", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::SquareRoot, "keire.math.square_root", "Square Root", "Math",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::All, 4},
            NodeDescriptor{ShaderGraphNodeKind::ReciprocalSquareRoot, "keire.math.reciprocal_square_root",
                           "Reciprocal Square Root", "Math", ShaderGraphValueType::Scalar, ShaderGraphShaderStage::All,
                           4},
            NodeDescriptor{ShaderGraphNodeKind::Exponential2, "keire.math.exponential_2", "Exponential 2", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Logarithm2, "keire.math.logarithm_2", "Logarithm 2", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Tangent, "keire.math.tangent", "Tangent", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::ArcSine, "keire.math.arc_sine", "Arc Sine", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::ArcCosine, "keire.math.arc_cosine", "Arc Cosine", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::ArcTangent2, "keire.math.arc_tangent_2", "Arc Tangent 2", "Math"},
            NodeDescriptor{ShaderGraphNodeKind::Cross, "keire.vector.cross", "Cross Product", "Vector",
                           ShaderGraphValueType::Vector3},
            NodeDescriptor{ShaderGraphNodeKind::Distance, "keire.vector.distance", "Distance", "Vector",
                           ShaderGraphValueType::Vector3},
            NodeDescriptor{ShaderGraphNodeKind::Reflect, "keire.vector.reflect", "Reflect", "Vector",
                           ShaderGraphValueType::Vector3},
            NodeDescriptor{ShaderGraphNodeKind::Refract, "keire.vector.refract", "Refract", "Vector",
                           ShaderGraphValueType::Vector3, ShaderGraphShaderStage::All, 8},
            NodeDescriptor{ShaderGraphNodeKind::AppendVector, "keire.vector.append", "Append Vector", "Vector",
                           ShaderGraphValueType::Vector4},
            NodeDescriptor{ShaderGraphNodeKind::ComponentMask, "keire.vector.component_mask", "Component Mask",
                           "Vector", ShaderGraphValueType::Vector4},
            NodeDescriptor{ShaderGraphNodeKind::UV1, "keire.input.uv1", "UV1", "Coordinates",
                           ShaderGraphValueType::Vector2, VertexAndFragment},
            NodeDescriptor{ShaderGraphNodeKind::WorldTangent, "keire.input.world_tangent", "World Tangent", "Inputs",
                           ShaderGraphValueType::Vector3, VertexAndFragment},
            NodeDescriptor{ShaderGraphNodeKind::CameraPosition, "keire.input.camera_position", "Camera Position",
                           "Inputs", ShaderGraphValueType::Vector3, ShaderGraphShaderStage::Fragment},
            NodeDescriptor{ShaderGraphNodeKind::ObjectPosition, "keire.input.object_position", "Object Position",
                           "Inputs", ShaderGraphValueType::Vector3, VertexAndFragment},
            NodeDescriptor{ShaderGraphNodeKind::Time, "keire.input.time", "Time", "Inputs",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::Fragment},
            NodeDescriptor{ShaderGraphNodeKind::DeltaTime, "keire.input.delta_time", "Delta Time", "Inputs",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::Fragment},
            NodeDescriptor{ShaderGraphNodeKind::ScreenPosition, "keire.input.screen_position", "Screen Position",
                           "Coordinates", ShaderGraphValueType::Vector2, ShaderGraphShaderStage::Fragment},
            NodeDescriptor{ShaderGraphNodeKind::DerivativeX, "keire.math.derivative_x", "Derivative X", "Math",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::Fragment},
            NodeDescriptor{ShaderGraphNodeKind::DerivativeY, "keire.math.derivative_y", "Derivative Y", "Math",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::Fragment},
            NodeDescriptor{ShaderGraphNodeKind::FilterWidth, "keire.math.filter_width", "Filter Width", "Math",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::Fragment, 2},
            NodeDescriptor{ShaderGraphNodeKind::DepthFade, "keire.scene.depth_fade", "Depth Fade", "Scene",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::Fragment, 6},
            NodeDescriptor{ShaderGraphNodeKind::Luminance, "keire.color.luminance", "Luminance", "Color",
                           ShaderGraphValueType::Color},
            NodeDescriptor{ShaderGraphNodeKind::HueShift, "keire.color.hue_shift", "Hue Shift", "Color",
                           ShaderGraphValueType::Color, ShaderGraphShaderStage::Fragment, 12},
            NodeDescriptor{ShaderGraphNodeKind::Checkerboard, "keire.procedural.checkerboard", "Checkerboard",
                           "Procedural", ShaderGraphValueType::Color, ShaderGraphShaderStage::Fragment, 8},
            NodeDescriptor{ShaderGraphNodeKind::VoronoiNoise, "keire.procedural.voronoi", "Voronoi Noise", "Procedural",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::Fragment, 36},
            NodeDescriptor{ShaderGraphNodeKind::Panner, "keire.coordinates.panner", "Panner", "Coordinates",
                           ShaderGraphValueType::Vector2, ShaderGraphShaderStage::Fragment, 4},
            NodeDescriptor{ShaderGraphNodeKind::PolarCoordinates, "keire.coordinates.polar", "Polar Coordinates",
                           "Coordinates", ShaderGraphValueType::Vector2, VertexAndFragment, 12},
            NodeDescriptor{ShaderGraphNodeKind::SphereMask, "keire.utility.sphere_mask", "Sphere Mask", "Utility",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::All, 8},
            NodeDescriptor{ShaderGraphNodeKind::RadialGradient, "keire.procedural.radial_gradient", "Radial Gradient",
                           "Procedural", ShaderGraphValueType::Scalar, ShaderGraphShaderStage::All, 8},
            NodeDescriptor{ShaderGraphNodeKind::LinearGradient, "keire.procedural.linear_gradient", "Linear Gradient",
                           "Procedural", ShaderGraphValueType::Scalar, ShaderGraphShaderStage::All, 4},
            NodeDescriptor{ShaderGraphNodeKind::Contrast, "keire.color.contrast", "Contrast", "Color",
                           ShaderGraphValueType::Color, ShaderGraphShaderStage::All, 4},
            NodeDescriptor{ShaderGraphNodeKind::Saturation, "keire.color.saturation", "Saturation", "Color",
                           ShaderGraphValueType::Color, ShaderGraphShaderStage::All, 6},
            NodeDescriptor{ShaderGraphNodeKind::BlendOverlay, "keire.color.blend_overlay", "Overlay Blend", "Color",
                           ShaderGraphValueType::Color, ShaderGraphShaderStage::All, 12},
            NodeDescriptor{ShaderGraphNodeKind::Blackbody, "keire.color.blackbody", "Blackbody", "Color",
                           ShaderGraphValueType::Color, ShaderGraphShaderStage::All, 24},
            NodeDescriptor{ShaderGraphNodeKind::ReflectionVector, "keire.input.reflection_vector", "Reflection Vector",
                           "Inputs", ShaderGraphValueType::Vector3, ShaderGraphShaderStage::Fragment, 4},
            NodeDescriptor{ShaderGraphNodeKind::FacingRatio, "keire.surface.facing_ratio", "Facing Ratio", "Surface",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::Fragment, 8},
            NodeDescriptor{ShaderGraphNodeKind::Dither, "keire.utility.dither", "Dither", "Utility",
                           ShaderGraphValueType::Scalar, ShaderGraphShaderStage::Fragment, 6},
            NodeDescriptor{ShaderGraphNodeKind::GradientNoise, "keire.procedural.gradient_noise", "Gradient Noise",
                           "Procedural", ShaderGraphValueType::Scalar, ShaderGraphShaderStage::Fragment, 30},
            NodeDescriptor{ShaderGraphNodeKind::Wave, "keire.procedural.wave", "Wave", "Procedural",
                           ShaderGraphValueType::Scalar, VertexAndFragment, 6},
            NodeDescriptor{ShaderGraphNodeKind::TriplanarSample, "keire.texture.triplanar_sample", "Triplanar Sample",
                           "Textures", ShaderGraphValueType::Color, ShaderGraphShaderStage::Fragment, 18},
            NodeDescriptor{ShaderGraphNodeKind::TextureSampleLevel, "keire.texture.sample_level_2d",
                           "Sample Texture 2D Level", "Textures", ShaderGraphValueType::Color,
                           ShaderGraphShaderStage::Fragment, 4},
            NodeDescriptor{ShaderGraphNodeKind::HeightToNormal, "keire.surface.height_to_normal", "Height To Normal",
                           "Surface", ShaderGraphValueType::Vector3, ShaderGraphShaderStage::Fragment, 10},
            NodeDescriptor{ShaderGraphNodeKind::FlattenNormal, "keire.surface.flatten_normal", "Flatten Normal",
                           "Surface", ShaderGraphValueType::Vector3, ShaderGraphShaderStage::Fragment, 6},
            NodeDescriptor{ShaderGraphNodeKind::MakeMaterialAttributes, "keire.attributes.make",
                           "Make Material Attributes", "Material Attributes", ShaderGraphValueType::MaterialAttributes,
                           ShaderGraphShaderStage::Fragment, 4},
            NodeDescriptor{ShaderGraphNodeKind::BreakMaterialAttributes, "keire.attributes.break",
                           "Break Material Attributes", "Material Attributes", ShaderGraphValueType::MaterialAttributes,
                           ShaderGraphShaderStage::Fragment, 2},
            NodeDescriptor{ShaderGraphNodeKind::BlendMaterialAttributes, "keire.attributes.blend",
                           "Blend Material Attributes", "Material Layers", ShaderGraphValueType::MaterialAttributes,
                           ShaderGraphShaderStage::Fragment, 36},
            NodeDescriptor{ShaderGraphNodeKind::StandardSurfaceBsdf, "keire.bsdf.standard_surface",
                           "Standard Surface BSDF", "BSDF", ShaderGraphValueType::Bsdf,
                           ShaderGraphShaderStage::Fragment, 6},
            NodeDescriptor{ShaderGraphNodeKind::ClearCoatBsdf, "keire.bsdf.clear_coat", "Clear Coat BSDF", "BSDF",
                           ShaderGraphValueType::Bsdf, ShaderGraphShaderStage::Fragment, 4},
            NodeDescriptor{ShaderGraphNodeKind::SheenBsdf, "keire.bsdf.sheen", "Sheen BSDF", "BSDF",
                           ShaderGraphValueType::Bsdf, ShaderGraphShaderStage::Fragment, 6},
            NodeDescriptor{ShaderGraphNodeKind::SubsurfaceBsdf, "keire.bsdf.subsurface", "Subsurface BSDF", "BSDF",
                           ShaderGraphValueType::Bsdf, ShaderGraphShaderStage::Fragment, 6},
            NodeDescriptor{ShaderGraphNodeKind::TransmissionBsdf, "keire.bsdf.transmission", "Transmission BSDF",
                           "BSDF", ShaderGraphValueType::Bsdf, ShaderGraphShaderStage::Fragment, 8},
            NodeDescriptor{ShaderGraphNodeKind::BsdfToMaterialAttributes, "keire.bsdf.to_material_attributes",
                           "BSDF To Material Attributes", "Material Attributes", ShaderGraphValueType::Bsdf,
                           ShaderGraphShaderStage::Fragment, 2},
        };
    } // namespace

    std::span<const ShaderGraphNodeDescriptor> ShaderGraphNodeCatalog() noexcept { return ShaderGraphNodeDescriptors; }

    const ShaderGraphNodeDescriptor* FindShaderGraphNodeDescriptor(const std::string_view typeId) noexcept
    {
        const auto found = std::ranges::find(ShaderGraphNodeDescriptors, typeId, &ShaderGraphNodeDescriptor::TypeId);
        return found == ShaderGraphNodeDescriptors.end() ? nullptr : &*found;
    }

    std::string_view ShaderGraphNodeTypeId(const ShaderGraphNodeKind kind) noexcept
    {
        const auto found = std::ranges::find(ShaderGraphNodeDescriptors, kind, &ShaderGraphNodeDescriptor::Kind);
        return found == ShaderGraphNodeDescriptors.end() ? std::string_view{} : found->TypeId;
    }
} // namespace Keire
