PROJECT_IDENTIFIER=Keire
PROJECT_DISPLAY_NAME=Kéire
PROJECT_VERSION=0.3.1
PROJECT_NAMESPACE=Keire
PROJECT_MACRO_PREFIX=KEIRE
CORE_TARGET=KeireCore
CORE_DIRECTORY=KeireCore
CLIENT_TARGET=KeireClient
CLIENT_DIRECTORY=KeireClient
HUB_TARGET=KeireHub
HUB_DIRECTORY=KeireHub
TESTS_TARGET=KeireTests
TESTS_DIRECTORY=KeireTests
ARTIFACT_PREFIX=keire
REPOSITORY_SLUG=hcfgod/KeireEngine
