PROJECT_IDENTIFIER=CrossPlatformCoreClientTemplate
PROJECT_DISPLAY_NAME=C++ Cross-Platform Core-Client Template
PROJECT_NAMESPACE=Core
PROJECT_MACRO_PREFIX=CROSS_PLATFORM_CORE_CLIENT_TEMPLATE
CORE_TARGET=Core
CORE_DIRECTORY=Core
CLIENT_TARGET=Client
CLIENT_DIRECTORY=Client
TESTS_TARGET=Tests
TESTS_DIRECTORY=Tests
ARTIFACT_PREFIX=cross-platform-core-client
REPOSITORY_SLUG=hcfgod/C-Cross-Platform-Core-Client-Template
