#!/usr/bin/env python3
"""Generate the checked-in VFX capability reference from authoritative contracts."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

from runtime_vfx_catalog import load_runtime_catalog


SUPPORT_LABEL = {
    "Supported": "Supported",
    "GpuRequired": "GPU Required",
    "KeireEquivalent": "Kéire Equivalent",
    "Disabled": "Disabled",
}
BACKEND_LABEL = {
    "CpuOnly": "CPU Only",
    "CpuAndGpu": "CPU and GPU",
    "GpuRequired": "GPU Required",
}


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest", type=Path, default=Path("Docs/VfxParityManifest.json")
    )
    parser.add_argument(
        "--output", type=Path, default=Path("Docs/generated/VfxCapabilities.md")
    )
    parser.add_argument(
        "--check", action="store_true", help="Fail if the generated document is stale."
    )
    return parser.parse_args()


def escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render(manifest: dict[str, object]) -> str:
    runtime = load_runtime_catalog()
    entries = manifest["entries"]
    mapped_rows: dict[str, list[dict[str, object]]] = defaultdict(list)
    for entry in entries:
        implementation = entry["keire"]["implementation"]
        if implementation:
            mapped_rows[implementation].append(entry)

    manifest_support = Counter(entry["keire"]["support"] for entry in entries)
    runtime_support = Counter(SUPPORT_LABEL[entry.support] for entry in runtime)
    lines = [
        "# Generated VFX Capabilities",
        "",
        "<!-- Generated by Scripts/Vfx/generate_vfx_capabilities.py. Do not edit by hand. -->",
        "",
        "This reference is generated from the runtime node catalog and the frozen Unity 6.3 LTS parity manifest. "
        "The [VFX authoring guide](../Vfx.md) explains workflows; the "
        "[machine-readable parity manifest](../VfxParityManifest.json) is the catalog authority.",
        "",
        "## Closure Summary",
        "",
        "| Contract | Supported | GPU Required | Kéire Equivalent | Disabled | Total |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
        (
            f"| Unity parity rows | {manifest_support['Supported']} | {manifest_support['GPU Required']} | "
            f"{manifest_support['Kéire Equivalent']} | {manifest_support['Disabled']} | {len(entries)} |"
        ),
        (
            f"| Runtime descriptors | {runtime_support['Supported']} | {runtime_support['GPU Required']} | "
            f"{runtime_support['Kéire Equivalent']} | {runtime_support['Disabled']} | {len(runtime)} |"
        ),
        "",
        "A runtime descriptor can be fully supported by Kéire while remaining a **Kéire Equivalent** in the parity "
        "manifest when Unity exposes broader polymorphic signatures or different authoring settings.",
        "",
        "## Production Slices",
        "",
        "| Slice | Backend | Implementations | Samples | Tests |",
        "| --- | --- | ---: | --- | --- |",
    ]
    for production_slice in manifest["productionSlices"]:
        lines.append(
            f"| {escape(production_slice['name'])} | {escape(production_slice['backendTier'])} | "
            f"{len(production_slice['implementations'])} | {escape(', '.join(production_slice['samples']))} | "
            f"{escape(', '.join(production_slice['tests']))} |"
        )

    lines.extend(
        [
            "",
            "## Runtime Node Catalog",
            "",
            "| Type ID | Label | Class | Runtime support | Backend | Enabled Unity rows |",
            "| --- | --- | --- | --- | --- | ---: |",
        ]
    )
    for node in runtime:
        enabled_rows = sum(
            row["keire"]["support"] != "Disabled" for row in mapped_rows[node.type_id]
        )
        lines.append(
            f"| `{escape(node.type_id)}` | {escape(node.label)} | {escape(node.node_class)} | "
            f"{escape(SUPPORT_LABEL[node.support])} | {escape(BACKEND_LABEL[node.backend])} | {enabled_rows} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    options = arguments()
    try:
        manifest = json.loads(options.manifest.read_text(encoding="utf-8"))
        encoded = render(manifest)
        if options.check:
            if (
                not options.output.is_file()
                or options.output.read_text(encoding="utf-8") != encoded
            ):
                print(
                    f"Generated VFX capability reference is stale: {options.output}",
                    file=sys.stderr,
                )
                return 1
            print(f"Generated VFX capability reference is current: {options.output}")
            return 0
        options.output.parent.mkdir(parents=True, exist_ok=True)
        options.output.write_text(encoded, encoding="utf-8", newline="\n")
        print(f"Generated {options.output}")
        return 0
    except (OSError, KeyError, TypeError, ValueError, json.JSONDecodeError) as error:
        print(f"VFX capability generation failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
